name: Build and push image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install deps and build
        run: |
          npm install
          npm run build

      - name: Build and push image
        uses: tvrcgo/docker-builder@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: tvrcgo/registry-web:latest
